### ISSUE TITLE
Base64 mode gives TypeError: Cannot read property 'baseFolder' of undefined

### ISSUE THREAD

**Issue by LifeLifeLP** [mamylinx/ep_image_insert#1]
Thank you for this great Plugin, i hope this can be fixed easy as adding pictures to pads makes them so much more usefull.
If there is anything more in can provide to help id be happy to do so.

How:
Open a new pad
Click the picture add icon in the menu
Select the example picture
Error:
Picture does not get added, at the bottom of the page is a white and empty textbox
Error is added to the log

Full error from log:
```
[2023-04-09 19:57:12.718] [ERROR] console - TypeError: Cannot read property 'baseFolder' of undefined
    at /home/lifelifelp/etherpad-lite/node_modules/ep_image_insert/index.js:79:52
    at Layer.handle [as handle_request] (/home/lifelifelp/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lifelifelp/etherpad-lite/src/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/lifelifelp/etherpad-lite/src/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/lifelifelp/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
    at /home/lifelifelp/etherpad-lite/src/node_modules/express/lib/router/index.js:281:22
    at param (/home/lifelifelp/etherpad-lite/src/node_modules/express/lib/router/index.js:354:14)
    at param (/home/lifelifelp/etherpad-lite/src/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/lifelifelp/etherpad-lite/src/node_modules/express/lib/router/index.js:410:3)
    at next (/home/lifelifelp/etherpad-lite/src/node_modules/express/lib/router/index.js:275:10)
```

Client: Up to date Windows 10 with Edge 112
Server: Update Debian 11 (in VMware) with Etherpad 1.8.18 on Node.js v14.21.3 & npm 6.14.18

No other plugins are install, the only change i made is to add this at the end of the settings file.

```
"ep_image_insert": {
    "fileTypes": ["jpeg", "jpg", "bmp", "gif", "png"],
    "maxFileSize": 5000000
}
```

Here is the picture i used for testing:
![OWSLA_SPACE](https://user-images.githubusercontent.com/13691155/230789402-6704617d-58a4-471c-839c-d3672a7b63ac.png)
And the log from console:
[log.txt](https://github.com/mamylinx/ep_image_insert/files/11186057/log.txt)

**Comment by mamylinx** [comment]
Thank you for spotting this issue. 
You need to specify storage type as `base 64` the settings.json file. I forget to note it in the README.
It would looks like:
`"ep_image_insert": {
    "storage":{
       "type": "base64",
     },
    "fileTypes": ["jpeg", "jpg", "bmp", "gif", "png"],
    "maxFileSize": 5000000
}`

Fixed at https://github.com/mamylinx/ep_image_insert/commit/a8dcdcde791ac65023592ffcef038c29fa2f9d3f
